use crate::decompiler_prototype::pcode::{OpCode, PcodeOp, AddressSpace};
use crate::decompiler_prototype::optimizer::{OptimizationRule, OptimizerContext};



///
/// (V & c1) & c2 => V & (c1 & c2)
/// (V | c1) | c2 => V | (c1 | c2)
pub struct RuleAndOrLump;

impl OptimizationRule for RuleAndOrLump {
    fn target_opcodes(&self) -> Vec<OpCode> {
        vec![OpCode::IntAnd, OpCode::IntOr, OpCode::IntXor]
    }

    fn apply(&self, op: &mut PcodeOp, _context: &mut OptimizerContext) -> bool {
        if op.inputs.len() < 2 {
            return false;
        }

        // Skip if input is not constant
        if op.inputs[1].space != AddressSpace::Const {
            return false;
        }

        // Check if input is generated by same Op (SSA chains)



        false // Not implemented
    }

    fn name(&self) -> &str {
        "RuleAndOrLump"
    }
}
